import ImageHandler as ih
from ImageHandler import cv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

loader = ih.ImageLoader('bilddaten\Dosenoeffner')
loader.AddDirRealPath('bilddaten\Flaschenoeffner')
loader.AddDirRealPath('bilddaten\Korkenzieher')
# loader.AddDirRealPath('train\Dosenoeffner')
# loader.AddDirRealPath('train\Flaschenoeffner')
# loader.AddDirRealPath('train\Korkenzieher')
for i in range(1):
    loader.MakeSampleEntrys(4)
    changer = ih.ImageChanger(loader.sampleEntrysPath, 0, False)
    changer.FrameByWidth(400)
    changer.BilateralFilter(10,10)
    changer.Normieren()
    changer.ColorMerkmale(sigma=1)
    # changer.ShowAll()
    changer.BrightTresh()
    # changer.ShowAll()
    changer.Bordering(100)
    # changer.ShowAll()
    changer.Dilation(7,2)
    # changer.ShowAll()
    changer.Erode(7,2)
    changer.ShowAll()
    # changer.CannyNorm(tres1=127,tres2=255, edge=20)
    # changer.AdaptiveCanny(edge=4)
    # changer.ShowAll()
    changer.Contures(type1=cv.RETR_TREE,type2=cv.CHAIN_APPROX_NONE,epsyValue=0.005)
    changer.ShowAll()
loader.AddColumnsToSample(changer.contureValues)
loader.PrintSampleEntrys()
loader.DeleteColumnFromSample('name')
loader.DeleteColumnFromSample('index')
loader.DeleteColumnFromSample('path')
loader.DeleteColumnFromSample('directoryPath')
loader.DeleteColumnFromSample('assignment')
loader.PrintSampleEntrys()
loader.PrintSamplesToCSV()